import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { makeCfg, makeWorld } from './helpers.js';
import { ROOT_DIR, publicConfig } from '../src/config.js';
import { createExecutionAdapter, ExecutionAdapter, PaperExecutionAdapter } from '../src/engine/execution.js';
import { PositionManager } from '../src/engine/positions.js';

test('PAPER_TRADING=false refuses to start', () => {
    assert.throws(() => makeCfg({ PAPER_TRADING: 'false' }), /not supported/);
});

test('only the paper adapter can be created', () => {
    const cfg = makeCfg();
    assert.equal(createExecutionAdapter(cfg).mode, 'PAPER');
    assert.throws(() => createExecutionAdapter(cfg, 'LIVE'), /Only PAPER/);
    assert.throws(() => createExecutionAdapter({ ...cfg, LIVE_TRADING_ENABLED: true }), /live trading is disabled/);
    assert.throws(() => createExecutionAdapter({ ...cfg, PAPER_TRADING: false }), /live trading is disabled/);
    assert.throws(() => new ExecutionAdapter(), /abstract/);
    assert.ok(Object.isFrozen(new PaperExecutionAdapter(cfg)));
});

test('position manager rejects any non-paper adapter', () => {
    const w = makeWorld();
    assert.throws(() => new PositionManager({ ...w, adapter: { mode: 'LIVE' } }), /paper execution adapter/);
});

test('no broker SDK or order endpoint exists in the code base', () => {
    const pkg = JSON.parse(fs.readFileSync(path.join(ROOT_DIR, 'package.json'), 'utf8'));
    const deps = Object.keys({ ...pkg.dependencies, ...pkg.optionalDependencies });
    for (const d of deps) assert.doesNotMatch(d, /kite|zerodha|upstox|angel|smartapi|fyers|dhan|ibkr|alpaca|binance|ccxt/i);
    const walk = (dir) => fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => (e.isDirectory() ? walk(path.join(dir, e.name)) : [path.join(dir, e.name)]));
    for (const f of walk(path.join(ROOT_DIR, 'src')).filter((f) => f.endsWith('.js'))) {
        const src = fs.readFileSync(f, 'utf8');
        assert.doesNotMatch(src, /placeOrder|place_order|\/orders\/regular|api\.kite|api\.upstox/i, f);
    }
});

test('public config never contains secrets', () => {
    process.env.GEMINI_API_KEY = 'test-secret-value-should-not-leak';
    try {
        const pc = publicConfig(makeCfg());
        const s = JSON.stringify(pc);
        assert.doesNotMatch(s, /test-secret-value/);
        assert.equal(pc.aiConfigured, true);
        assert.equal(pc.paperTrading, true);
        assert.equal(pc.liveTrading, false);
    } finally {
        delete process.env.GEMINI_API_KEY;
    }
});

test('dashboard shows PAPER TRADING MODE and LIVE TRADING DISABLED', () => {
    // Source HTML (always present); the built copy is generated by `npm run build`.
    const html = fs.readFileSync(path.join(ROOT_DIR, 'web/index.html'), 'utf8');
    assert.match(html, /PAPER TRADING MODE/);
    assert.match(html, /LIVE TRADING DISABLED/);
});

test('defaults match the brief', () => {
    const c = makeCfg();
    assert.equal(c.LOT_SIZE, 1);
    assert.equal(c.MIN_TARGET, 10);
    assert.equal(c.STOP_LOSS_PERCENT, 5);
    assert.equal(c.TRAILING_ENABLED, true);
    assert.throws(() => makeCfg({ STOP_LOSS_PERCENT: 6 }), /out of range/, 'stop can be tightened, never loosened past 5%');
});
